finance_tracker/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'finance_tracker'

urlpatterns = [
    path('', views.finance_tracker_home, name='home'),
    path('dashboard/', views.finance_tracker_dashboard, name='dashboard'),
    path('transactions/', views.TransactionListView.as_view(), name='transaction-list'),
    path('categories/', views.CategoryList.as_view(), name='categories'),
    path('category/detail/', views.CategoryDetailView.as_view(), name='category-detail'),
    path('components/upload-notify/', views.upload_notify_component, name='upload_notify_component'),
    path('upload/', views.upload_statement, name='file_upload'),
    path('transactions/<int:pk>/update/', views.TransactionUpdateView.as_view(), name='edit_transaction'),
    path('transactions/<int:pk>/delete/', views.TransactionDeleteView.as_view(), name='delete_transaction'),
    # API's
    # path('transactions_json/', views.transaction_list_json, name='transaction_list_json'),
    path('transactions_api/', views.TransactionListAPIView.as_view(), name='transactions_api'),
    path('transactions_api/<int:pk>/', views.TransactionDetailAPIView.as_view(), name='transactions_detail_api'),
    path('category_api/', views.CategoryListAPIView.as_view(), name='category_api'),
    path('category_api/<int:pk>', views.CategoryDetailAPIView.as_view(), name='category_detail_api'),
    path('category_expense_json/', views.category_expenses_json, name='category_expense_json'),
    path('monthly_expense_json/', views.monthly_expense_json, name='monthly_expense_json'),
    path('income_total_json/', views.income_total_json, name='income_total_json'),
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('finance_tracker/', include('finance_tracker.urls')), 
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()
    urlpatterns += [
        re_path(r'^favicon\.ico$', serve, {
                'document_root': settings.STATIC_ROOT,
                'path': 'favicon.ico',
            }
        ),
    ]

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio' # needed for namespacing

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('projects/<int:pk>/', views.project_redirect, name='project_redirect'),
]

users/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'users'

urlpatterns = [
    path('profile/', views.user_profile, name='profile_home'),
    path('profile/update_profile/', views.UserSettings.as_view(), name='update_profile'),
]

portfolio/models.py
from django.db import models
from django.urls import reverse


class Technology(models.Model):
    name = models.CharField(max_length=100, unique=True, help_text="Name of the technology (e.g., Python, Django)")
    icon = models.ImageField(upload_to='technology_icons/', blank=True, null=True)
    
    class Meta:
        verbose_name_plural = "Technologies"
    
    def __str__(self):
        return self.name
    
    
class Project(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='project_images/', blank=True, null=True)
    github = models.URLField(blank=True, null=True)
    technologies = models.ManyToManyField(Technology, blank=True, help_text="Technology used in this project")
    TYPES = (
        ('FINANCE', 'Fiinance Tracker'),
        ('BLOG', 'Personal Blog'),
        ('WORKER_MANAGEMENT', 'Contract Worker Management'),
        ('PORTFOLIO_SITE', 'Portfolio Site'),
        ('OTHER', 'Other')
        )
    
    type = models.CharField(max_length=50,
                  choices=TYPES,
                  default="OTHER")
    
    def get_absolute_url(self):
        return reverse('project_detail', args=[str(self.id)]) 
    
    def __str__(self):
        return self.title

portfolio/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Project

# Create your views here.
def home(request):
    projects = Project.objects.all() # Get all prpjects from database
    return render(request, 'portfolio/index.html', {'projects': projects}) # Renders the index.html template and pass the projects to the template


def project_redirect(request, pk):
    project = get_object_or_404(Project, pk=pk)  # Get the specific project

    if project.type == 'FINANCE':
        return redirect('finance_tracker:home') 
    # elif project.type == 'BLOG':
    #     return redirect('blog:home') 
    # elif project.type == 'FIT_WEATHER':
    #     return redirect('weather_app:home') 
    # elif project.type == 'BUSINESS_FINDER':
    #     return redirect('business_finder:home') 
    else:
        # Handle other project types
        return redirect('home') # Or another appropriate view


def about(request):
    return render(request, 'portfolio/about.html') # Renders the index.html template and pass the projects to the template

portfolio/templates/portfolio/components/about.html
{% load static %} 
{% comment %} <div class="about-content">
    <div class="about-image">
        <img src="{% static 'portfolio/images/al&lou.png' %}" alt="Lucas and wife, Alycia">
    </div>
        <div class="about-text">
            <h2>About Me</h2>
            <p>Hey everyone! I'm Lucas, and I'm passionate about building things – whether it's a strong client relationship, a successful business venture, or a clean, functional line of code.  I've spent the last 7+ years honing my skills in B2B sales, learning the art of understanding client needs and delivering solutions that drive real results.  I thrive on the challenge of exceeding expectations and building partnerships that last.</p>

            <p>One of the things I appreciate most about programming is the constant learning and evolution.  It mirrors the dynamic nature of the business world, where adaptability and continuous improvement are key. I'm currently working through online courses and tutorials to deepen my programing knowledge and explore frameworks like Django and React. Recently completed two MOOCs from the University of Helsinki on Python, Django 4 Everybody by Dr. Charles Severance, and I'm currently working my way through The Odin Project.</p>

            <p>My background is a blend of business and hands-on experience.  Beyond my sales roles at companies like Aerotek, I've also embraced the entrepreneurial spirit, founding and running businesses like Force Pro Fitness, Mealworkx, and the RSCUED, a purpose-driven apparel brand focused on animal adoption awareness.  These ventures have given me invaluable experience in all aspects of business operations, from marketing and website development to managing suppliers and fulfillment.</p>

            <p>I believe that the combination of my business acumen and my growing technical skills provides a unique perspective. I'm eager to connect with other developers and professionals who share my passion for innovation and building things that matter.  Feel free to reach out – let's connect!</p>
            </p>
        </div>
</div> {% endcomment %}

<section class="section about-section gray-bg" id="about">
    <div class="container">
        <div class="row align-items-center justify-content-around flex-row-reverse">
            <div class="col-lg-6">
                <div class="about-text">
                    <h1 class="display-4 fw-bold dark-color">Building Digital Experiences That Matter.</h1>
                    <h3 class="fw-semibold" style="color: green">Full-Stack Web Developer <small>(in the making)</small></h3>
                    <p>
                        As a new and enthusiastic web developer, I'm specializing in crafting robust and user-centric applications. My learning journey involves understanding how elegant front-end design and powerful back-end functionality blend to create seamless digital experiences. 
                    </p>
                    <p>
                        I'm particularly interested in tackling real-world problems and collaborating with teams to transform their visions into tangible solutions. My previous experience in sales equips me with valuable communication skills and a strong awareness of client pain points and end-user objectives, which I aim to utilize in the development process.
                    </p>
                    <div class="btn-bar">
                        <a href="{% url 'portfolio:home' %}#contact-me" id="btn_1" class="btn btn-success me-2">Let's Chat! <i class="bi bi-file-earmark-person"></i></a>
                        {% comment %} <a href="{% url 'portfolio:home' %}#contact-me" id="btn_2" class="btn btn-outline-success">Resume <i class="bi bi-file-earmark-person"></i></a> {% endcomment %}
                    </div>
                </div>
            </div>
            <div class="col-lg-5 text-center bg-white">
                <div class="about-img">
                    <img src="{% static 'portfolio/images/banner_headshot.png' %}" style="width: 480px">
                </div>
            </div>
        </div>
    </div>
</section>

portfolio/templates/portfolio/components/contact_form.html
<span class="display-4 fw-bold dark-color mb-3">Contact Me!</span>
  <form>
    <div class="mb-3">
      <label for="name" class="form-label">Name</label>
      <input
        type="text"
        class="form-control"
        id="name"
        placeholder="Enter your name"
      />
    </div>
    <div class="mb-3">
      <label for="email" class="form-label">Email address</label>
      <input
        type="email"
        class="form-control"
        id="email"
        placeholder="Enter your email"
      />
    </div>
    <div class="mb-3">
      <label for="message" class="form-label">Message</label>
      <textarea class="form-control" id="message" rows="3"></textarea>
    </div>
    <button id="contact-btn" type="submit" class="btn">Submit</button>
  </form>

portfolio/templates/portfolio/components/footer.html
<div class="container vh-75">
  <section class="mt-5">
    <div class="row text-center d-flex justify-content-center pt-5">
      <div class="col-md-2">
        <h6 class="text-uppercase font-weight-bold">
          <a href="{% url 'portfolio:home' %}#home" class="text-white">Home</a>
        </h6>
      </div>

      <div class="col-md-2">
        <h6 class="text-uppercase font-weight-bold">
          <a href="{% url 'portfolio:home' %}#about-me" class="text-white"
            >About me</a
          >
        </h6>
      </div>

      <div class="col-md-2">
        <h6 class="text-uppercase font-weight-bold">
          <a
            href="{% url 'portfolio:home' %}#projects-section"
            class="text-white"
            >Projects</a
          >
        </h6>
      </div>

      <div class="col-md-2">
        <h6 class="text-uppercase font-weight-bold">
          <a href="{% url 'portfolio:home' %}#contact-me" class="text-white"
            >Contact me</a
          >
        </h6>
      </div>
    </div>
  </section>

  <hr class="my-5" />

  <section class="text-center mb-5">
    <a href="" class="text-white me-4">
      <i class="fab fa-facebook-f"></i>
    </a>
    <a href="" class="text-white me-4">
      <i class="fab fa-twitter"></i>
    </a>
    <a href="" class="text-white me-4">
      <i class="fab fa-google"></i>
    </a>
    <a href="" class="text-white me-4">
      <i class="fab fa-instagram"></i>
    </a>
    <a href="" class="text-white me-4">
      <i class="fab fa-linkedin"></i>
    </a>
    <a href="" class="text-white me-4">
      <i class="fab fa-github"></i>
    </a>
  </section>
</div>

<div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.29)">
  © 2025 Copyright:
  <a class="text-white" href="https://lucaspatriquin.com/"
    >LucasPatriquin.org</a
  >
</div>

portfolio/templates/portfolio/components/hero_banner.html
{% load static %}

<div class="container-fuid bg-dark text-light min-vh-75 mt-5">
    <div class="container px-4">
        <div class="row flex-lg-row-reverse align-items-center g-5">
            <div class="col-sm-10 col-md-8 col-lg-6 order-lg-first order-last">
                <img id="hero-img" src="{% static 'portfolio/images/banner_headshot.png' %}" class="d-block mx-lg-auto img-fluid" alt="Lucas Patriquin Headshot" loading="lazy">
            </div>
            <div id="left-hb" class="col-lg-5 col-md-8 col-sm-10">
                <h4 class="lh-1 mb-3">Hi, I'm Lucas!</h4>
                <h4 class="display-3 fw-bold lh-1 mb-3">Welcome to my Code Lab</h4>
                <p class="lead">A glimpse into my coding journey, fueled by an unhealthy amount of coffee and a healthy dose of curiosity.</p>
                <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                    <a href="{% url 'portfolio:home' %}#projects-section" class="text-decoration-none">
                        <button type="button" class="btn btn-success btn-lg px-4 me-md-2">My Work <i class="bi bi-rocket-takeoff"></i></button>
                    </a>
                    <a href="{% url 'portfolio:home' %}#contact-me" class="text-decoration-none">
                        <button type="button" class="btn btn-outline-light btn-lg px-4">Connect <i class="bi bi-envelope-check"></i></button>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

portfolio/templates/portfolio/components/nav_bar.html
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top border-bottom border-body" data-bs-theme="dark">
     <div class="container-fluid">
         <a class="navbar-brand fw-bold" href="{% url 'portfolio:home' %}">LP's PORTFOLIO</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'portfolio:home' %}">Home</a>
                    </li>
                    <li class="nav-item dropdown">  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Projects
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdown"> 
                        <li><a class="dropdown-item" href="{% url 'portfolio:home' %}#projects-section">All Projects</a></li><li><hr class="dropdown-divider"></li>  
                        <li><a class="dropdown-item" href="{% url 'finance_tracker:home' %}">Personal Finance Tracker</a></li>
                        <li><a class="dropdown-item" href="#">Happiness - Coming Soon</a></li>
                        <li><a class="dropdown-item" href="#">Business Locator - Coming Soon</a></li>
                        <li><a class="dropdown-item" href="#">Blog - Coming Soon</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'portfolio:home' %}#about-me">About Me</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'portfolio:home' %}#contact-me">Contact</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

portfolio/templates/portfolio/components/nav_bar2.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <button
    class="navbar-toggler"
    type="button"
    data-bs-toggle="collapse"
    data-bs-target="#mainNavbarCollapse"
    aria-controls="mainNavbarCollapse"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div
    class="collapse navbar-collapse justify-content-md-center"
    id="mainNavbarCollapse"
  >
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'portfolio:home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'portfolio:home' %}#about-me"
          >About Me</a
        >
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'portfolio:home' %}#contact-me"
          >Contact</a
        >
      </li>
      <li class="nav-item dropdown">
        <a
          class="nav-link dropdown-toggle"
          href="#"
          id="navbarDropdown"
          role="button"
          data-bs-toggle="dropdown"
          aria-expanded="false"
        >
          Projects
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">AI Spending Tracker</a>
          <a class="dropdown-item" href="#">Blog</a>
          <a class="dropdown-item" href="#">Contract Worker Management</a>
          <hr class="dropdown-divider" />
          <a
            class="dropdown-item"
            href="{% url 'portfolio:home' %}#projects-section"
            >All Projects</a
          >
        </div>
      </li>
    </ul>
  </div>
</nav>

portfolio/templates/portfolio/components/navbar.html
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top border-bottom border-body" data-bs-theme="dark">
     <div class="container-fluid">
         <a class="navbar-brand fw-bold" href="{% url 'portfolio:home' %}">LP's PORTFOLIO</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'portfolio:home' %}">Home</a>
                    </li>
                    <li class="nav-item dropdown">  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Projects
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdown"> 
                        <li><a class="dropdown-item" href="{% url 'portfolio:home' %}#projects-section">All Projects</a></li><li><hr class="dropdown-divider"></li>  
                        <li><a class="dropdown-item" href="{% url 'finance_tracker:home' %}">Personal Finance Tracker</a></li>
                        <li><a class="dropdown-item" href="#">Happiness - Coming Soon</a></li>
                        <li><a class="dropdown-item" href="#">Business Locator - Coming Soon</a></li>
                        <li><a class="dropdown-item" href="#">Blog - Coming Soon</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'portfolio:home' %}#about-me">About Me</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'portfolio:home' %}#contact-me">Contact</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

portfolio/templates/portfolio/components/navbar_2.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" aria-label="LP Portfolio Navbar">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#LPnavbar" aria-controls="LPnavbarp" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-md-center" id="LPnavbar">
          <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link text-gradient" href="{% url 'portfolio:home' %}#home">Portfolio Home</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-gradient"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
                >
                Projects
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'finance_tracker:home' %}">Evergreen Financial</a>
                    <a class="dropdown-item" href="#">LP's Blog</a>
                    <a class="dropdown-item" href="#">Restaurant Loyalty Program</a>
                    <a class="dropdown-item" href="#">Portfolio Site</a>
                    <hr class="dropdown-divider" />
                    <a
                    class="dropdown-item"
                    href="{% url 'portfolio:home' %}#projects-section"
                    >All Projects</a
                    >
                </div>
                <li class="nav-item">
                <a class="nav-link text-gradient" href="{% url 'portfolio:home' %}#about-me">About Me</a>
                </li>
                <li class="nav-item">
                <a class="nav-link text-gradient" href="{% url 'portfolio:home' %}#contact-me">Contact</a>
            </li>
        </div>
      </div>
</nav>

portfolio/templates/portfolio/components/project_card.html
<div class="container mb-5">
        <h1 class="display-4 fw-bold dark-color text-center mt-5 mb-3">My Projects</h1>

        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-5 mb-4 mx-auto">  
            {% if projects %}
            {% for project in projects %}
                <div class="col text-center">  
                    <div id="project-card" class="card h-100">
                        <a href="{% url 'portfolio:project_redirect' pk=project.pk %}">

                            {% if project.image %}
                                <img id="project-img" src="{{ project.image.url }}" class="card-img-top img-fluid" alt="{{ project.title }}">
                            {% endif %}

                            <div id="pc-body" class="card-body d-flex flex-column">
                                <h5 id="pc-title" class="card-title">{{ project.title }}</h5>
                                <p id="project-description" class="card-text">{{ project.description|truncatechars:150 }}</p>
                            </div>
                            
                            <div class="mt-auto mb-2">
                                {% if project.github %}
                                    <a href="{{ project.github }}" target="blank" class="text-decoration-none">
                                        <i class="bi bi-github"> github repo</i>
                                    </a>
                                {% endif %}
                            </div>

                            <div class="technologies mb-3">
                                {% for technology in project.technologies.all %}
                                    <img src="{{ technology.icon.url }}" alt="{{ technology.name }} icon" title="{{ technology.name }}" class="technology-icon">
                                {% endfor %}
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}

        {% else %}
        <p>No projects added yet.</p>
        {% endif %}

    </div>
</div>