finance_tracker/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'finance_tracker'

urlpatterns = [
    path('', views.finance_tracker_home, name='home'),
    path('dashboard/', views.finance_tracker_dashboard, name='dashboard'),
    path('transactions/', views.TransactionListView.as_view(), name='transaction-list'),
    path('categories/', views.CategoryList.as_view(), name='categories'),
    path('category/detail/', views.CategoryDetailView.as_view(), name='category-detail'),
    path('components/upload-notify/', views.upload_notify_component, name='upload_notify_component'),
    path('upload/', views.upload_statement, name='file_upload'),
    path('transactions/<int:pk>/update/', views.TransactionUpdateView.as_view(), name='edit_transaction'),
    path('transactions/<int:pk>/delete/', views.TransactionDeleteView.as_view(), name='delete_transaction'),
    # API's
    # path('transactions_json/', views.transaction_list_json, name='transaction_list_json'),
    path('transactions_api/', views.TransactionListAPIView.as_view(), name='transactions_api'),
    path('transactions_api/<int:pk>/', views.TransactionDetailAPIView.as_view(), name='transactions_detail_api'),
    path('category_api/', views.CategoryListAPIView.as_view(), name='category_api'),
    path('category_api/<int:pk>', views.CategoryDetailAPIView.as_view(), name='category_detail_api'),
    path('category_expense_json/', views.category_expenses_json, name='category_expense_json'),
    path('monthly_expense_json/', views.monthly_expense_json, name='monthly_expense_json'),
    path('income_total_json/', views.income_total_json, name='income_total_json'),
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('finance_tracker/', include('finance_tracker.urls')), 
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()
    urlpatterns += [
        re_path(r'^favicon\.ico$', serve, {
                'document_root': settings.STATIC_ROOT,
                'path': 'favicon.ico',
            }
        ),
    ]

users/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'users'

urlpatterns = [
    path('profile/', views.user_profile, name='profile_home'),
    path('profile/update_profile/', views.UserSettings.as_view(), name='update_profile'),
]

finance_tracker/models.py
from django.db import models
from django.conf import settings
from django.db.models import Sum

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)
    
    class Meta:
        verbose_name_plural = "Categories"
        
    def __str__(self):
        return self.name
    
class Transaction(models.Model):
    date = models.DateField(null=True, blank=True)
    description = models.CharField(max_length=255)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    notes = models.TextField(max_length=500, null=True, blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.date} - {self.description} - {self.category} - ${self.amount} - {self.owner}"

finance_tracker/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Field, Row, Column


class UploadFileForm(forms.Form):        
    file = forms.FileField(required=True, help_text="Please upload your bank statement as a CSV file")

    # Form Helper (crispy)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = "upload_form"
        self.helper.form_method = "post"
        self.helper.form_class = "mt-5"
        self.helper.label_class = 'visually-hidden'
        self.helper.field_class = '' 
        
        self.helper.layout = Layout(
            Row(
                Column(Field('file'), css_class='form-group col-md-9'),
                Column(Submit('submit', 'Upload', css_class='btn-secondar'), 
                       css_class='form-group col-md-3 d-flex align-self-start justify-content-center'),
                css_class='form-row'
                ),
    
        )

finance_tracker/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.urls import reverse_lazy

# Django Views
from django.views.generic import TemplateView, View
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, DeleteView


# Django Models
from django.db import models
from django.db.models import Sum, Min, Max
from .models import Transaction, Category
from django.db.models import Q, Sum, Count
from django.db.models.functions import TruncMonth


# Django Forms
from django import forms
from .forms import UploadFileForm

# Django Auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Misc
from django.utils import formats
from .utils import categorize_transaction, add_header
from io import StringIO
from decimal import Decimal
from datetime import datetime
import csv

# Pagination
from .mixins import ViewPaginatorMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .pagination import CustomPageNumberPagination

# Serializers
from .serializers import TransactionSerializer, CategorySerializer

# Rest Framework
from rest_framework import generics, permissions, filters
from rest_framework.response import Response
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated



def finance_tracker_home(request):
    return render(request, 'finance_tracker/landing_page.html')


@login_required
def finance_tracker_dashboard(request):
    expense_transactions = Transaction.objects.exclude(
        category__name='Income').filter(
            owner=request.user)
    
    expense_total_aggregation = expense_transactions.aggregate(
        total_expense_amount=Sum('amount'))
    
    # Pass months to template for drop down btn selector
    months_data = expense_transactions.annotate(
        month=TruncMonth('date')).values('month')
    month_names = []
    seen_months = set() #prevent duplicates.
    for item in months_data:
        month_date = item['month']
        month_name = month_date.strftime("%B %Y") # ex: Jan 2024
        if month_name not in seen_months:
            month_names.append((month_date, month_name))
            seen_months.add(month_name)
    
    # Custom sort function to sort by month and year
    def month_sort_key(item):
        return item[0].year, item[0].month

    month_names.sort(key=month_sort_key)
    months = [name for date, name in month_names] 
        
    income_transactions = Transaction.objects.filter(
        owner=request.user,
        category__name='Income')
    
    income_total_aggregation = income_transactions.aggregate(
        total_income_amount=Sum('amount')
     )
    
    top3_categories = Category.objects.exclude(
            name='Income').annotate(
            total_amount=Sum('transaction__amount', filter=models.Q(
                transaction__owner=request.user))
            ).exclude(total_amount=0 or None).order_by('total_amount')[:5]
    
    context = {
        'categories': top3_categories,
        'income_summary': income_total_aggregation,
        'expense_summary': expense_total_aggregation,
        'months': months
    }
    
    return render(request, 'finance_tracker/dashboard.html', context)


class TransactionListView(LoginRequiredMixin, ListView):
    template_name = 'finance_tracker/transaction_list.html'
    model = Transaction
    context_object_name = 'transactions'
    

# class TransactionListView(LoginRequiredMixin, ListView):
#     paginate_by = 10
#     model = Transaction
#     ordering = ['-date'] 
    
#     def get_queryset(self): 
#         queryset = super().get_queryset().filter(owner=self.request.user)
#         search_term = self.request.GET.get('search_term')
#         clear_search = self.request.GET.get('clear_search')
#         category_id = self.request.GET.get('category_id')
        
#         if category_id:
#             queryset = super().get_queryset().filter(
#                 category_id=category_id)
        
#         if clear_search: # Check if 'clear_search' parameter is present
#             return queryset
        
#         if search_term: 
#             queryset = queryset.filter(
#                 Q(description__icontains=search_term) |
#                 Q(category__name__icontains=search_term)
#             )
            
#         return queryset

#     def get_context_data(self, **kwargs):
#         try:
#             context = super().get_context_data(**kwargs)
            
#             # Categories for filter btn
#             categories = Category.objects.annotate(
#                 total_amount=Sum('transaction__amount', filter=models.Q(
#                     transaction__owner=self.request.user))
#             ).exclude(total_amount__isnull=True).exclude(total_amount=0).order_by('name')

#             # Return start and end date for filtered transactions for stat bar
#             end_date = self.get_queryset().latest('date').date
#             start_date = self.get_queryset().earliest('date').date
            
#             # Return queryset length (transactions) for stats bar
#             length = self.get_queryset().count
            
#             # Return transactions sum for stats bar
#             category_id = self.request.GET.get('category_id')
#             if category_id:
#                 if category_id == "52":
#                     expense_transactions_sum = self.get_queryset().aggregate(
#                         total_expense_amount=Sum('amount'))
#                 else:
#                     expense_transactions_sum = self.get_queryset().exclude(
#                         category__name='Income').aggregate(
#                         total_expense_amount=Sum('amount'))
#             else:
#                 expense_transactions_sum = self.get_queryset().exclude(
#                     category__name='Income').aggregate(
#                     total_expense_amount=Sum('amount'))
            
#             # Pass data to template
#             context['end_date'] = end_date
#             context['start_date'] = start_date
#             context['length'] = length
#             context['expense_summary'] = expense_transactions_sum
#             context['categories'] = categories
#             # context['filtered_transactions'] = filtered_transactions
#         except:
#             print(f'No Transactions')
#             return
        
#         return context


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = [
            "date",
            "description",
            "category",
            "notes",
            "amount"
        ]
        widgets = {
            'notes': forms.Textarea(attrs={'rows': 2, 'cols': 40}),  # Adjust rows and cols as needed
        }
        

class TransactionUpdateView(LoginRequiredMixin, UpdateView):
    model = Transaction
    form_class = TransactionForm
    template_name_suffix = "_update_form"
    
    # Disable the date field and amount from user
    def get_form(self, form_class = None):
        form = super().get_form(form_class)
        form.fields['date'].disabled = True
        form.fields['amount'].disabled = True
        return form
    
    def get_success_url(self):
        return reverse_lazy('finance_tracker:transaction-list-api')
    
    
class TransactionDeleteView(LoginRequiredMixin, DeleteView):
    model = Transaction
    
    def get_success_url(self):
        return reverse_lazy('finance_tracker:transaction-list-api')
    

class CategoryList(LoginRequiredMixin, ListView):
    template_name = 'finance_tracker/category_list.html'
    model = Category
    context_object_name = 'categories'


class CategoryDetailView(LoginRequiredMixin, ListView):
    template_name = 'finance_tracker/category_detail.html'
    model = Category
    context_object_name = 'categories'
    

def upload_notify_component(request):
    return render(request, 'finance_tracker/components/upload_notify.html')
    

@login_required
def upload_statement(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)

        if form.is_valid():
            uploaded_file = form.cleaned_data['file']
            
            filename= uploaded_file.name
            print(filename)

            if 'cibc' in filename.lower():
                try:
                    file_with_header = add_header(uploaded_file)
                    file_content = file_with_header.read().decode('utf-8') 
                except NameError as e:
                    print(f'Cannot read file, error: {e}')
                except:
                    print(f'Another error has occured')
            else:
                file_content = uploaded_file.read().decode('utf-8') 
                

            csvfile =StringIO(file_content) # creates a StringIO object to process it without saving on disk
            reader = csv.DictReader(csvfile)
            
            transactions_to_create = []
            
            for row in reader:
                date_str = row.get('Date')
                description = row.get('Sub-description')
                amount_str = row.get('Amount')

                # Basic data cleaning and conversion
                if date_str:
                    try:
                        date = datetime.strptime(date_str, '%Y-%m-%d')  # Adjust format if needed
                    except ValueError:
                        print(f"Invalid date format for transaction: {description}")
                        continue

                if amount_str:
                    try:
                        amount = Decimal(amount_str.replace(',', ''))
                    except ValueError:
                        print(f"Invalid amount format for transaction: {description}")
                        continue

                # Categorize transactions

finance_tracker/templates/finance_tracker/landing_page.html
{% extends 'finance_tracker/simple_base.html' %} 
{% load static %}

{% block title %} Evergreen Financial - Finance Tracker {% endblock %}

{% block description %} Track and manage your personal finances all in one place with Evergreen Financial {% endblock %} 

{% block content %}
<div class="landing-page-container">
    <div class="call-to-action">
        <div class="app-logo">
            <i class="bi bi-app-indicator"></i> </div>
        <h1 class="appName">Evergreen Financial</h1>
        <span id="changingWord" class="fw-bold tagline lead"></span></p>
        <div class="auth-buttons">
            <a href="{% url 'finance_tracker:dashboard' %}" class="btn btn-primary btn-lg rounded-pill login-btn">Log In</a>
            <a href="{% url 'account_signup' %}" class="btn btn-outline-secondary btn-lg rounded-pill signup-btn">Sign Up</a>
            <p id="terms-agreement-text" class="mt-2 small">By continuing, you agree to our <a href="#">Terms</a> & <a href="#">Privacy Policy</a>.</p>
        </div>
    </div>
</div>
  {% endblock %}

  {% block extra_js %}
  <script src="{% static 'finance_tracker/js/landing_page.js' %}"></script>
  {% endblock %}

finance_tracker/templates/finance_tracker/navbar_2.html
<div class="offcanvas offcanvas-start w-25 offcanvas-dark bg-dark" tabindex="-1" id="offcanvas" data-bs-keyboard="false" data-bs-backdrop="false">
    <div class="offcanvas-header">
        <h6 class="offcanvas-title d-none d-sm-block" id="offcanvas">Menu</h6>
        <button  type="button" class="btn-close text-reset btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body px-0">
        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-start" id="menu">
            <li class="nav-item">
                <a href="{% url 'finance_tracker:home' %}" class="nav-link text-truncate text-light">
                    <i class="fs-5 bi-house"></i><span class="ms-1 d-none d-sm-inline"> Home</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'finance_tracker:dashboard' %}" class="nav-link text-truncate text-light">
                    <i class="fs-5 bi-speedometer2"></i><span class="ms-1 d-none d-sm-inline"> Dashboard</span> </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'finance_tracker:transaction-list' %}" class="nav-link text-truncate text-light">
                    <i class="fs-5 bi-table"></i><span class="ms-1 d-none d-sm-inline"> Transactions</span></a>
            </li>
            <li class="nav-item">
                <a href="{% url 'finance_tracker:file_upload' %}" class="nav-link text-truncate text-light">
                    <i class="fs-5 bi bi-cloud-arrow-up-fill"></i><span class="ms-1 d-none d-sm-inline"> Upload</span></a>
                </li>
{% comment %} --------- Account ---------- {% endcomment %}
            <li class="dropdown">
                <a href="#" class="nav-link dropdown-toggle text-truncate text-light" id="dropdown" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fs-5 bi bi-person-circle"></i><span class="ms-1 d-none d-sm-inline">Account</span>
                </a>
                <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdown">
                    <li><a class="dropdown-item" href="{% url 'account_signup' %}">Sign Up</a></li>
                    <li><a class="dropdown-item" href="{% url 'account_login' %}">Login</a></li>
                    <li><a class="dropdown-item" href="{% url 'account_reset_password' %}">Reset Password</a></li>
                </ul>
            </li> 
            </ul>
        </div>
    </div>
        
        

finance_tracker/templates/finance_tracker/transaction_list.html
{% extends 'finance_tracker/base.html' %}
{% load static %}

{% block content %}
  <div class="container container-transaction-page mx-auto px-sm-0">
    <div class="mb-5 mt-2">
      <h2 class="justin-content-center"><i class="bi bi-list-ul"></i> Transactions</h2>
    </div>

        {% comment %}------ Header ------{% endcomment %}
        <div class="row d-flex mt-4">
            {% comment %}------ Stats Bar ------{% endcomment %}
            <div class="stats-bar hstack col-lg-9 col-sm-12 justify-content-center align-self-center mx-auto" style="height: auto;">
                <div class="flex-grow-1 py-2 px-4">
                    <p class="fw-lighter">Date Range</p>
                    <h4 id="date-range"></h4>
                </div> 
                <div class="vr"></div>
                <div class="flex-grow-1 py-2 px-4">
                    <p class="fw-lighter">Transactions</p>
                    <h4 id="transaction-count"></h4>
                </div> 
                <div class="vr"></div>
                        <div class="flex-grow-1 py-2 px-4">
                            <p class="fw-lighter">Total</p>
                            <h4 id="stats-total"></h4>
                        </div>
            </div>
        </div>

        <div class="row justify-content-between mt-5">
            {% comment %}------ Search Field ------{% endcomment %}
            <div class="col-lg-3 col-md-6 col-sm-12 align-self-end">
                <form method="get" class="mb-3">
                    <div class="input-group" style="--search-icon-url: url({% static 'finance_tracker/images/transaction_list/search.svg' %});">
                        <input id="search-bar"type="text" class="form-control transaction-search-field" placeholder="Search transactions..." name="search_term" transaction-search-bar/>
                    </div>
                </form>
            </div>
            {% comment %}------ Category Filter Menu ------{% endcomment %}
            <div class="col-auto ms-auto clearFilterDiv">
                <span class="btn clearFilterBtn hide">Clear Filter</span>
            </div>
            <div class="col-auto">
                <div class="dropdown filter-badge open">
                    <a
                        class="btn btn-sm text-light dropdown-toggle"
                        type="button"
                        id="filter-badge"
                        data-bs-toggle="dropdown"
                        aria-haspopup="true"
                        aria-expanded="false"
                    >
                    <i class="bi bi-filter"></i> Category Filters
                    </a>
                    <div class="dropdown-menu filter-dropdown-menu" aria-labelledby="triggerId">
                        </div>
                </div>
            </div>
        </div> 
        
        <div id="transaction-table" class="table-responsive mt-3">
            <table class="table table-hover" style="width: 100%;">
                <thead>
                    <tr>
                        <th scope="col">Date</th>
                        <th scope="col">Description</th>
                        <th scope="col">Category</th>
                        <th scope="col">Amount</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody class="table-group-divider table align-middle" transaction-row-container></tbody>
            </table>

            {% comment %}------ Loader ------{% endcomment %}
            <div class="loader-div">
                <div class="loader"></div>
            </div>
        </div> 

        
        {% comment %}------ Pagination ------{% endcomment %}
        <div class="text-center pagination-div">
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    <li class="page-item previous-page disabled">
                        <a class="page-link previousUrl" href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo; Previous</span>
                        </a>
                    </li>
                    <li class="page-item active " aria-current="page">
                        <a class="page-link current-page" href="#"></a>
                    </li>
                    <li class="page-item next-page disabled">
                        <a class="page-link nextUrl" href="#" aria-label="Next">
                            <span aria-hidden="true">Next &raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>

        </div>
    </div>

    
    {% comment %} <a class="me-1 mb-1">
        <span class="badge rounded-pill category-filter-badge"></span>
    </a> {% endcomment %}
    
    {% comment %}------ Filter Btn ------{% endcomment %}
    <template filterButtonTemplate>
        <a class="dropdown-item category-filter-badge"></a>
    </template>

    {% comment %}------ Transaction List Table ------{% endcomment %}
    <template transaction-row-template>
        <tr>
            <td class="transaction-date">
                <span class="desktop-date" transaction-desktop-date></span> 
                <span class="mobile-date" transaction-mobile-date></span>
            </td>
            <td class="transaction-description" transaction-description></td>
            <td><span id="category-pill" class="badge badge-pill category-badge text-light" transaction-category></span></td>
            <td transaction-amount></td>
            <td class="transaction-action">
                <a href="#" data-edit-url="{% url 'finance_tracker:edit_transaction' pk='0' %}">
                    <i class="bi bi-pencil-square text-success edit-link"></i>
                </a> |
                <a href="#" data-delete-url="{% url 'finance_tracker:delete_transaction' pk='0' %}">
                    <i class="bi bi-trash3-fill text-secondary delete-link"></i>
                </a>
            </td>
        </tr>
    </template>
{% endblock %}

{% block extra_js %}
  <script type="module" src="{% static 'finance_tracker/js/transactions_list/main.js' %}"></script>
{% endblock %}

finance_tracker/templates/finance_tracker/transaction_list_api.html
{% extends 'finance_tracker/base.html' %}
{% load static %}

{% block content %}
  <div class="container container-fluid-mobile mx-auto px-sm-0">
    <div class="mb-5 mt-2">
      <h2 class="justin-content-center"><i class="bi bi-list-ul"></i> Transactions</h2>
    </div>

        {% comment %}------ Header ------{% endcomment %}
        <div class="row d-flex mt-4">
            {% comment %}------ Stats Bar ------{% endcomment %}
            <div class="stats-bar hstack col-lg-9 col-sm-12 justify-content-center align-self-center mx-auto" style="height: auto;">
                <div class="flex-grow-1 py-2 px-4">
                    <p class="fw-lighter">Date Range</p>
                    <h4 id="date-range"></h4>
                </div> 
                <div class="vr"></div>
                <div class="flex-grow-1 py-2 px-4">
                    <p class="fw-lighter">Transactions</p>
                    <h4 id="transaction-count"></h4>
                </div> 
                <div class="vr"></div>
                        <div class="flex-grow-1 py-2 px-4">
                            <p class="fw-lighter">Total</p>
                            <h4 id="stats-total"></h4>
                        </div>
            </div>
        </div>

        <div class="row justify-content-between mt-5">
            {% comment %}------ Search Field ------{% endcomment %}
            <div class="col-lg-3 col-md-6 col-sm-12 align-self-end">
                <form method="get" class="mb-3">
                    <div class="input-group" style="--search-icon-url: url({% static 'finance_tracker/images/transaction_list/search.svg' %});">
                        <input id="search-bar"type="text" class="form-control transaction-search-field" placeholder="Search transactions..." name="search_term" transaction-search-bar/>
                    </div>
                </form>
            </div>
            {% comment %}------ Category Filter Menu ------{% endcomment %}
            <div class="col-auto ms-auto clearFilterDiv">
                <span class="btn clearFilterBtn hide">Clear Filter</span>
            </div>
            <div class="col-auto">
                <div class="dropdown filter-badge open">
                    <a
                        class="btn btn-sm text-light dropdown-toggle"
                        type="button"
                        id="filter-badge"
                        data-bs-toggle="dropdown"
                        aria-haspopup="true"
                        aria-expanded="false"
                    >
                    <i class="bi bi-filter"></i> Category Filters
                    </a>
                    <div class="dropdown-menu filter-dropdown-menu" aria-labelledby="triggerId">
                        </div>
                </div>
            </div>
        </div> 
        
        <div id="transaction-table" class="table-responsive mt-3">
            <table class="table table-hover" style="width: 100%;">
                <thead>
                    <tr>
                        <th scope="col">Date</th>
                        <th scope="col">Description</th>
                        <th scope="col">Category</th>
                        <th scope="col">Amount</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody class="table-group-divider table align-middle" transaction-row-container></tbody>
            </table>

            {% comment %}------ Loader ------{% endcomment %}
            <div class="loader-div">
                <div class="loader"></div>
            </div>
        </div> 

        
        {% comment %}------ Pagination ------{% endcomment %}
        <div class="text-center pagination-div">
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    <li class="page-item previous-page disabled">
                        <a class="page-link previousUrl" href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo; Previous</span>
                        </a>
                    </li>
                    <li class="page-item active " aria-current="page">
                        <a class="page-link current-page" href="#"></a>
                    </li>
                    <li class="page-item next-page disabled">
                        <a class="page-link nextUrl" href="#" aria-label="Next">
                            <span aria-hidden="true">Next &raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>

        </div>
    </div>

    
    {% comment %} <a class="me-1 mb-1">
        <span class="badge rounded-pill category-filter-badge"></span>
    </a> {% endcomment %}
    
    {% comment %}------ Filter Btn ------{% endcomment %}
    <template filterButtonTemplate>
        <a class="dropdown-item category-filter-badge"></a>
    </template>

    {% comment %}------ Transaction List Table ------{% endcomment %}
    <template transaction-row-template>
        <tr>
            <td class="transaction-date">
                <span class="desktop-date" transaction-desktop-date></span> 
                <span class="mobile-date" transaction-mobile-date></span>
            </td>
            <td class="transaction-description" transaction-description></td>
            <td><span id="category-pill" class="badge badge-pill category-badge text-light" transaction-category></span></td>
            <td transaction-amount></td>
            <td class="transaction-action">
                <a href="#" data-edit-url="{% url 'finance_tracker:edit_transaction' pk='0' %}">
                    <i class="bi bi-pencil-square text-success edit-link"></i>
                </a> |
                <a href="#" data-delete-url="{% url 'finance_tracker:delete_transaction' pk='0' %}">
                    <i class="bi bi-trash3-fill text-secondary delete-link"></i>
                </a>
            </td>
        </tr>
    </template>
{% endblock %}

{% block extra_js %}
  <script type="module" src="{% static 'finance_tracker/js/transaction_list_main.js' %}"></script>
{% endblock %}