my_site/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('finance_tracker/', include('finance_tracker.urls')), 
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()
    urlpatterns += [
        re_path(r'^favicon\.ico$', serve, {
                'document_root': settings.STATIC_ROOT,
                'path': 'favicon.ico',
            }
        ),
    ]

users/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'users'

urlpatterns = [
    path('profile/', views.user_profile, name='profile_home'),
    path('profile/update_profile/', views.UserSettings.as_view(), name='update_profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/users/user_<id>/<filename>
    return "users/user_{0}/{1}".format(instance.user.id, filename)
    
    
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    avatar = models.ImageField(upload_to=user_directory_path, blank=True, null=True)
    
    def __str__(self):
        return f'Profile for {self.user.username}'
    
    
# Save instance of UserProfile when new user is created
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

users/forms.py
from django import forms
from .models import UserProfile
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, HTML, Div, Field

class ProfileUpdateForm(forms.ModelForm):
    first_name = forms.CharField(max_length=32)
    last_name = forms.CharField(max_length=32)
    email = forms.EmailField(max_length=50, required=False)
    
    class Meta:
        model = UserProfile
        fields = ['avatar']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-3'
        self.helper.field_class = 'col-lg-9'
        self.helper.layout = Layout(
                HTML("""
                    <div class="form-group text-center mb-3">
                        {% if form.instance.avatar %}
                            <img src="{{ form.instance.avatar.url }}" alt="Current Avatar" class="img-fluid my-3" style="max-width: 200px; max-height: 200px; border-radius: 50%;">
                        {% else %}
                            <p>No Profile Picture</p>
                            <i class="bi bi-person-circle" style="font-size: 5rem;"></i> <p class="text-muted">Default Avatar</p>
                        {% endif %}
                    </div>
                """),
                'avatar',
                Div(
                    Field('first_name', label="First Name", css_class='form-control-lg'),
                    'first_name.errors',
                    Field('last_name', label="Last Name", css_class='form-control-lg'),
                    'last_name.errors'
                ),
                Field('email', label="Email", help_text="We'll never share your email with anyone else."    ),
                Submit('submit', 'Save Changes', css_class="btn btn-dark btn-block"),
            )

users/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView, ModelFormMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from .models import UserProfile
from .forms import ProfileUpdateForm
from django.urls import reverse

@login_required
def user_profile(request):
    user = request.user
    user_profile = request.user.profile
    context = {
        'user': user,
        'user_profile': user_profile
    }
    return render(request, 'users/profile.html', context)



class UserSettings(LoginRequiredMixin, UpdateView, ModelFormMixin):
    template_name = 'users/update_profile.html'
    form_class = ProfileUpdateForm

    def get_object(self, queryset=None):
        return self.request.user.profile

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['instance'] = self.get_object()
        kwargs['initial'] = {
            'first_name': self.request.user.first_name, 
            'last_name': self.request.user.last_name,
            'user_email': self.request.user.email
        }
        return kwargs

    def form_valid(self, form):
        print(form.cleaned_data) 
        user = self.request.user
        user.first_name = form.cleaned_data['first_name']
        user.last_name = form.cleaned_data['last_name']
        user.email = form.cleaned_data['email']
        print(user.__dict__)
        user.save()
        print(self.get_object().__dict__)
        form.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('users:profile_home')
    
    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)

users/templates/users/profile.html
{% extends "finance_tracker/base.html" %}
{% load static %}
{% load socialaccount %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'users/css/users.css' %}">
{% endblock extra_css%}

{% block title %}User Profile{% endblock %}

{% block content %}
<div class="container col-lg-9 col-sm-12  my-5">
    <div class="card shadow mb-4">
        <div class="card-header bg-secondary text-white">
            <i class="bi bi-person-circle me-2"></i> Your Profile Information
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-3 text-center py-5">
                    {% if user_profile.avatar %}
                        <img src="{{ user_profile.avatar.url }}" alt="Profile Avatar" class="img-fluid" style="max-width: 150px; max-height: 150px; border-radius: 50%;">
                    {% else %}
                        <p>No Profile Picture</p>
                        <i class="bi bi-person-circle" style="font-size: 5rem;"></i> <p class="text-muted">Default Avatar</p>
                    {% endif %}
                </div>
                <div class="col-md-8 ms-5 align-self-center">
                    <dl class="row">
                        <dt class="col-sm-3 fw-bold">Username:</dt>
                        <dd class="col-sm-9">{{ user.username }}</dd>

                        <dt class="col-sm-3 fw-bold">Email:</dt>
                        {% if user.email %}
                            <dd class="col-sm-9">{{ user.email }}</dd>
                        {% else %}
                            <dd class="col-sm-9">N/A</dd>
                        {% endif %}

                        <dt class="col-sm-3 fw-bold">First Name:</dt>
                        <dd class="col-sm-9">{{ user.first_name|default:"N/A" }}</dd>

                        <dt class="col-sm-3 fw-bold">Last Name:</dt>
                        <dd class="col-sm-9">{{ user.last_name|default:"N/A" }}</dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>

    <div class="card shadow mb-4">
        <div class="card-header bg-secondary text-white">
            <i class="bi bi-gear-fill me-2"></i> Account Actions
        </div>
        <div class="card-body">
            <ul class="list-unstyled">
                <li>
                    <a href="{% url 'users:update_profile' %}" class="btn btn-outline-secondary btn-sm mb-2">
                        <i class="bi bi-pencil-square"></i> Edit Profile
                    </a>
                </li>
                <li>
                    <a href="{% url 'account_change_password' %}" class="btn btn-outline-secondary btn-sm mb-2">
                        <i class="bi bi-lock-fill me-1"></i> Change Password
                    </a>
                </li>
                <li>
                    <a href="{% url 'account_logout' %}" class="btn btn-danger btn-sm">
                        <i class="bi bi-box-arrow-right me-1"></i> Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <div class="card shadow">
        <div class="card-header bg-secondary text-white">
            <i class="bi bi-person-plus-fill me-2"></i> Connect Social Accounts
        </div>
        <div class="card-body">
            <ul class="list-unstyled">
                {% get_social_accounts user as accounts %}
                    {% if accounts.google %}
                        <li>
                            <button class="btn btn-secondary btn-block mb-2" disabled>
                                <i class="bi bi-google me-1"></i> Google Account Connected
                            </button>
                        {% else %}
                            <a href="{% provider_login_url provider.id process='connect' %}" class="btn btn-outline-primary btn-block mb-2">
                                <i class="bi bi-google me-1"></i> Connect Google Account
                            </a>
                        </li>
                    {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/update_profile.html
{% extends 'finance_tracker/base.html' %} 
{% load crispy_forms_tags %} 
{% crispy profile_update_form %}
{% load static %} 

{% block title %}Update User Profile{%endblock %} 

{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-lg-8 col-xl-6">
            <div class="card shadow p-4">
                <div class="card-header bg-success text-white text-center">
                    <i class="bi bi-box-arrow-in-right me-2"></i> Update Profile
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {% crispy form %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}