finance_tracker/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'finance_tracker'

urlpatterns = [
    path('', views.finance_tracker_home, name='home'),
    path('dashboard/', views.finance_tracker_dashboard, name='dashboard'),
    path('transactions/', views.TransactionListView.as_view(), name='transaction-list'),
    path('categories/', views.CategoryList.as_view(), name='categories'),
    path('category/detail/', views.CategoryDetailView.as_view(), name='category-detail'),
    path('components/upload-notify/', views.upload_notify_component, name='upload_notify_component'),
    path('upload/', views.upload_statement, name='file_upload'),
    path('transactions/<int:pk>/update/', views.TransactionUpdateView.as_view(), name='edit_transaction'),
    path('transactions/<int:pk>/delete/', views.TransactionDeleteView.as_view(), name='delete_transaction'),
    # API's
    # path('transactions_json/', views.transaction_list_json, name='transaction_list_json'),
    path('transactions_api/', views.TransactionListAPIView.as_view(), name='transactions_api'),
    path('transactions_api/<int:pk>/', views.TransactionDetailAPIView.as_view(), name='transactions_detail_api'),
    path('category_api/', views.CategoryListAPIView.as_view(), name='category_api'),
    path('category_api/<int:pk>', views.CategoryDetailAPIView.as_view(), name='category_detail_api'),
    path('category_expense_json/', views.category_expenses_json, name='category_expense_json'),
    path('monthly_expense_json/', views.monthly_expense_json, name='monthly_expense_json'),
    path('income_total_json/', views.income_total_json, name='income_total_json'),
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('finance_tracker/', include('finance_tracker.urls')), 
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()
    urlpatterns += [
        re_path(r'^favicon\.ico$', serve, {
                'document_root': settings.STATIC_ROOT,
                'path': 'favicon.ico',
            }
        ),
    ]

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio' # needed for namespacing

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('projects/<int:pk>/', views.project_redirect, name='project_redirect'),
]

users/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'users'

urlpatterns = [
    path('profile/', views.user_profile, name='profile_home'),
    path('profile/update_profile/', views.UserSettings.as_view(), name='update_profile'),
]

finance_tracker/models.py
from django.db import models
from django.conf import settings
from django.db.models import Sum

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)
    
    class Meta:
        verbose_name_plural = "Categories"
        
    def __str__(self):
        return self.name
    
class Transaction(models.Model):
    date = models.DateField(null=True, blank=True)
    description = models.CharField(max_length=255)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    notes = models.TextField(max_length=500, null=True, blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.date} - {self.description} - {self.category} - ${self.amount} - {self.owner}"

finance_tracker/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Field, Row, Column


class UploadFileForm(forms.Form):        
    file = forms.FileField(required=True, help_text="Please upload your bank statement as a CSV file")

    # Form Helper (crispy)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = "upload_form"
        self.helper.form_method = "post"
        self.helper.form_class = "mt-5"
        self.helper.label_class = 'visually-hidden'
        self.helper.field_class = '' 
        
        self.helper.layout = Layout(
            Row(
                Column(Field('file'), css_class='form-group col-md-9'),
                Column(Submit('submit', 'Upload', css_class='btn-secondar'), 
                       css_class='form-group col-md-3 d-flex align-self-start justify-content-center'),
                css_class='form-row'
                ),
    
        )

finance_tracker/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.urls import reverse_lazy

# Django Views
from django.views.generic import TemplateView, View
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, DeleteView


# Django Models
from django.db import models
from django.db.models import Sum, Min, Max
from .models import Transaction, Category
from django.db.models import Q, Sum, Count
from django.db.models.functions import TruncMonth


# Django Forms
from django import forms
from .forms import UploadFileForm

# Django Auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Misc
from django.utils import formats
from .utils import categorize_transaction, add_header
from io import StringIO
from decimal import Decimal
from datetime import datetime
import csv

# Pagination
from .mixins import ViewPaginatorMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .pagination import CustomPageNumberPagination

# Serializers
from .serializers import TransactionSerializer, CategorySerializer

# Rest Framework
from rest_framework import generics, permissions, filters
from rest_framework.response import Response
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated



def finance_tracker_home(request):
    return render(request, 'finance_tracker/landing_page.html')


@login_required
def finance_tracker_dashboard(request):
    expense_transactions = Transaction.objects.exclude(
        category__name='Income').filter(
            owner=request.user)
    
    expense_total_aggregation = expense_transactions.aggregate(
        total_expense_amount=Sum('amount'))
    
    # Pass months to template for drop down btn selector
    months_data = expense_transactions.annotate(
        month=TruncMonth('date')).values('month')
    month_names = []
    seen_months = set() #prevent duplicates.
    for item in months_data:
        month_date = item['month']
        month_name = month_date.strftime("%B %Y") # ex: Jan 2024
        if month_name not in seen_months:
            month_names.append((month_date, month_name))
            seen_months.add(month_name)
    
    # Custom sort function to sort by month and year
    def month_sort_key(item):
        return item[0].year, item[0].month

    month_names.sort(key=month_sort_key)
    months = [name for date, name in month_names] 
        
    income_transactions = Transaction.objects.filter(
        owner=request.user,
        category__name='Income')
    
    income_total_aggregation = income_transactions.aggregate(
        total_income_amount=Sum('amount')
     )
    
    top3_categories = Category.objects.exclude(
            name='Income').annotate(
            total_amount=Sum('transaction__amount', filter=models.Q(
                transaction__owner=request.user))
            ).exclude(total_amount=0 or None).order_by('total_amount')[:5]
    
    context = {
        'categories': top3_categories,
        'income_summary': income_total_aggregation,
        'expense_summary': expense_total_aggregation,
        'months': months
    }
    
    return render(request, 'finance_tracker/dashboard.html', context)


class TransactionListView(LoginRequiredMixin, ListView):
    template_name = 'finance_tracker/transaction_list.html'
    model = Transaction
    context_object_name = 'transactions'
    

# class TransactionListView(LoginRequiredMixin, ListView):
#     paginate_by = 10
#     model = Transaction
#     ordering = ['-date'] 
    
#     def get_queryset(self): 
#         queryset = super().get_queryset().filter(owner=self.request.user)
#         search_term = self.request.GET.get('search_term')
#         clear_search = self.request.GET.get('clear_search')
#         category_id = self.request.GET.get('category_id')
        
#         if category_id:
#             queryset = super().get_queryset().filter(
#                 category_id=category_id)
        
#         if clear_search: # Check if 'clear_search' parameter is present
#             return queryset
        
#         if search_term: 
#             queryset = queryset.filter(
#                 Q(description__icontains=search_term) |
#                 Q(category__name__icontains=search_term)
#             )
            
#         return queryset

#     def get_context_data(self, **kwargs):
#         try:
#             context = super().get_context_data(**kwargs)
            
#             # Categories for filter btn
#             categories = Category.objects.annotate(
#                 total_amount=Sum('transaction__amount', filter=models.Q(
#                     transaction__owner=self.request.user))
#             ).exclude(total_amount__isnull=True).exclude(total_amount=0).order_by('name')

#             # Return start and end date for filtered transactions for stat bar
#             end_date = self.get_queryset().latest('date').date
#             start_date = self.get_queryset().earliest('date').date
            
#             # Return queryset length (transactions) for stats bar
#             length = self.get_queryset().count
            
#             # Return transactions sum for stats bar
#             category_id = self.request.GET.get('category_id')
#             if category_id:
#                 if category_id == "52":
#                     expense_transactions_sum = self.get_queryset().aggregate(
#                         total_expense_amount=Sum('amount'))
#                 else:
#                     expense_transactions_sum = self.get_queryset().exclude(
#                         category__name='Income').aggregate(
#                         total_expense_amount=Sum('amount'))
#             else:
#                 expense_transactions_sum = self.get_queryset().exclude(
#                     category__name='Income').aggregate(
#                     total_expense_amount=Sum('amount'))
            
#             # Pass data to template
#             context['end_date'] = end_date
#             context['start_date'] = start_date
#             context['length'] = length
#             context['expense_summary'] = expense_transactions_sum
#             context['categories'] = categories
#             # context['filtered_transactions'] = filtered_transactions
#         except:
#             print(f'No Transactions')
#             return
        
#         return context


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = [
            "date",
            "description",
            "category",
            "notes",
            "amount"
        ]
        widgets = {
            'notes': forms.Textarea(attrs={'rows': 2, 'cols': 40}),  # Adjust rows and cols as needed
        }
        

class TransactionUpdateView(LoginRequiredMixin, UpdateView):
    model = Transaction
    form_class = TransactionForm
    template_name_suffix = "_update_form"
    
    # Disable the date field and amount from user
    def get_form(self, form_class = None):
        form = super().get_form(form_class)
        form.fields['date'].disabled = True
        form.fields['amount'].disabled = True
        return form
    
    def get_success_url(self):
        return reverse_lazy('finance_tracker:transaction-list-api')
    
    
class TransactionDeleteView(LoginRequiredMixin, DeleteView):
    model = Transaction
    
    def get_success_url(self):
        return reverse_lazy('finance_tracker:transaction-list-api')
    

class CategoryList(LoginRequiredMixin, ListView):
    template_name = 'finance_tracker/category_list.html'
    model = Category
    context_object_name = 'categories'


class CategoryDetailView(LoginRequiredMixin, ListView):
    template_name = 'finance_tracker/category_detail.html'
    model = Category
    context_object_name = 'categories'
    

def upload_notify_component(request):
    return render(request, 'finance_tracker/components/upload_notify.html')
    

@login_required
def upload_statement(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)

        if form.is_valid():
            uploaded_file = form.cleaned_data['file']
            
            filename= uploaded_file.name
            print(filename)

            if 'cibc' in filename.lower():
                try:
                    file_with_header = add_header(uploaded_file)
                    file_content = file_with_header.read().decode('utf-8') 
                except NameError as e:
                    print(f'Cannot read file, error: {e}')
                except:
                    print(f'Another error has occured')
            else:
                file_content = uploaded_file.read().decode('utf-8') 
                

            csvfile =StringIO(file_content) # creates a StringIO object to process it without saving on disk
            reader = csv.DictReader(csvfile)
            
            transactions_to_create = []
            
            for row in reader:
                date_str = row.get('Date')
                description = row.get('Sub-description')
                amount_str = row.get('Amount')

                # Basic data cleaning and conversion
                if date_str:
                    try:
                        date = datetime.strptime(date_str, '%Y-%m-%d')  # Adjust format if needed
                    except ValueError:
                        print(f"Invalid date format for transaction: {description}")
                        continue

                if amount_str:
                    try:
                        amount = Decimal(amount_str.replace(',', ''))
                    except ValueError:
                        print(f"Invalid amount format for transaction: {description}")
                        continue

                # Categorize transactions

finance_tracker/templates/finance_tracker/components/contact.html
<section id="contact" class="ud-contact">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-xl-8 col-lg-7">
        <div class="ud-contact-content-wrapper">
          <div class="ud-contact-title">
            <span>CONTACT ME</span>
            <h1 class="fw-bold">
              LIKE MY WORK? <br />
              I'd love to hear from you!
            </h1>
            <a href="{% url 'portfolio:home' %}#contact-me" class="enter-site-btn btn rounded-pill btn-lg me-2">Message Me</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

finance_tracker/templates/finance_tracker/components/demo.html
{% load static %}
<section id="demo" class="ud-demo">
  <div class="container">
    <span>Video Walk-through</span>
    <h2>demo</h2>
    <p>
      A complete Walk-through of my EVERGREEN Personal Finance App. Please join
      me in reviewing the tech stack used, main features, and the overall goal
      of my project.
    </p>
  </div>
  <div class="container">
    <div class="ud-demo-wrapper wow fadeInUp" data-wow-delay=".2s">
      <div class="ud-demo-content">
        {% comment %} ----- Welcome Video ----- {% endcomment %}
        <div id="video-container">
          <div
            style="
              position: relative;
              padding-bottom: 56.25%;
              height: 0;
              overflow: hidden;
            "
          >
            <div style="position: relative; padding-bottom: 56.25%; height: 0">
              <iframe
                src="https://www.loom.com/embed/84b1b4fcd38247fc94b53c2c7e241402?sid=ac7cd639-e6be-43ca-8a99-2c1759cd72fa"
                frameborder="0"
                webkitallowfullscreen
                mozallowfullscreen
                allowfullscreen
                style="
                  position: absolute;
                  top: 0;
                  left: 0;
                  width: 100%;
                  height: 100%;
                "
              ></iframe>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

finance_tracker/templates/finance_tracker/components/features.html
{% load static %}

<section id="features" class="ud-features">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="ud-section-title">
            <span>Features</span>
            <h2>Main Features</h2>
            <p>
              EVERGREEN Was built to help you easily manage your day to day spending, main features include:
            </p>
          </div>
        </div>
      </div>
      <div class="row d-flex justify-content-between">
        <div class="col-xl-3 col-lg-3 col-sm-6">
          <div class="ud-single-feature wow fadeInUp" data-wow-delay=".15s">
            <div class="ud-feature-icon">
              <i class="lni lni-move"></i>
            </div>
            <div class="ud-feature-content">
              <h3 class="ud-feature-title">Easy Uploads!</h3>
              <p class="ud-feature-desc">
                Upload your bankstatements easily with one click.
              </p>
            </div>
          </div>
        </div>
        <div class="col-xl-3 col-lg-3 col-sm-6">
          <div class="ud-single-feature wow fadeInUp" data-wow-delay=".2s">
            <div class="ud-feature-icon">
              <i class="lni lni-layout"></i>
            </div>
            <div class="ud-feature-content">
              <h3 class="ud-feature-title">AI Categorization</h3>
              <p class="ud-feature-desc">
                Automatically categorize your spending transactions with our built in AI.
              </p>
            </div>
          </div>
        </div>
        <div class="col-xl-3 col-lg-3 col-sm-6">
          <div class="ud-single-feature wow fadeInUp" data-wow-delay=".25s">
            <div class="ud-feature-icon">
              <i class="lni lni-layers"></i>
            </div>
            <div class="ud-feature-content">
              <h3 class="ud-feature-title">Robust User Dashboard</h3>
              <p class="ud-feature-desc">
                Quickly review your spending with our detailed user dashboard.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

finance_tracker/templates/finance_tracker/components/header.html
{% load static %}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
        <nav class="navbar navbar-expand-lg">
            <a class="navbar-brand" href="index.html">
            <img src="{% static 'finance_tracker/images/logo/logo.png' %}" 
                alt="Logo" 
                data-logo-default="{% static 'finance_tracker/images/logo/logo.png' %}"
                data-logo-scroll="{% static 'finance_tracker/images/logo/logo-2.png' %}">
            </a>
            <button class="navbar-toggler">
            <span class="toggler-icon"> </span>
            <span class="toggler-icon"> </span>
            <span class="toggler-icon"> </span>
            </button>

            <div class="navbar-collapse">
            <ul id="nav" class="navbar-nav mx-auto">
                <li class="nav-item">
                <a class="lp-menu-scroll" href="#home">Home</a>
                </li>
                <li class="nav-item">
                <a class="menu-scroll" href="#demo">Demo</a>
                </li>
                <li class="nav-item">
                <a class="menu-scroll" href="#faq">FAQ</a>
                </li>
                <li class="nav-item">
                <a class="menu-scroll" href="#contact">Contact</a>
                </li>
            </ul>
            </div>

            <div class="navbar-btn d-none d-sm-inline-block ms-5 me-3">
                    <a href="{% url 'portfolio:home' %}" class="ud-main-btn ud-login-btn">
                        Portfolio
                    </a>
                </a>
            </div>
        </nav>
        </div>
    </div>
</div>

finance_tracker/templates/finance_tracker/components/hero.html
{% load static %}

<section class="ud-hero" id="home">
    <div class="container">
    <div class="row">
        <div class="col-lg-12">
        <div class="ud-hero-content wow fadeInUp" data-wow-delay=".2s">
            <h1 class="ud-hero-title">
            A Personal Finance Tracker with Budgeting and AI Categorizing
            </h1>
            <p class="ud-hero-desc">
            Monitor your personal finances and create monthly budgets, so you can build the future you deserve.
            </p>
            <ul class="ud-hero-buttons">
            <li>
                <a href="{% url 'finance_tracker:dashboard' %}" class="enter-site-btn btn rounded-pill btn-lg me-2">Get Started</a>
            </li>
            <li>
                <a href="#demo" class="view-demo-btn btn btn-outline-secondary rounded-pill">View Demo <i class="lni lni-arrow-right"></i></a>
                </a>
            </li>
            </ul>
        </div>
        
        <div class="ud-hero-image wow fadeInUp" data-wow-delay=".25s">
            <img src="{% static 'finance_tracker/images/hero/dotted-shape.svg' %}" alt="shape" class="shape shape-1" />
            <div id="carouselExampleAutoplaying" class="carousel slide carousel-dark" data-bs-ride="carousel">
                <div class="carousel-inner">
                  <div class="carousel-item active" data-bs-interval="4000">
                    <img src="{% static 'finance_tracker/images/hero/hero-1.png' %}" class="d-block w-100" alt="hero-image-1">
                  </div>
                  <div class="carousel-item" data-bs-interval="4000">
                    <img src="{% static 'finance_tracker/images/hero/hero-2.png' %}" class="d-block w-100" alt="...">
                  </div>
                  <div class="carousel-item" data-bs-interval="4000">
                    <img src="{% static 'finance_tracker/images/hero/hero-3.png' %}" class="d-block w-100" alt="...">
                  </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
              </div>
              <img src="{% static 'finance_tracker/images/hero/dotted-shape.svg' %}" alt="shape" class="shape shape-2" />
            </div>
        </div>
    </div>
    </div>
</section>

finance_tracker/templates/finance_tracker/components/pricing.html
{% load static %}

<section id="pricing" class="ud-pricing">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="ud-section-title mx-auto text-center">
            <h2>START FOR FREE!</h2>
            <p>
              Upload your expenses, create a budget, and start improving your life today. 
            </p>
          </div>
        </div>
      </div>

      <div class="row g-0 align-items-center justify-content-center">
        <div class="col-lg-4 col-md-6 col-sm-10">
          <div
            class="ud-single-pricing first-item wow fadeInUp"
            data-wow-delay=".15s">
            <div class="ud-pricing-header">
              <h3>START WITH OUR</h3>
              <h4>FREE PLAN</h4>
            </div>
            <div class="ud-pricing-body">
              <ul class="pricing-list">
                <li>1 User</li>
                <li>Upload 5 Files</li>
                <li>30-day access</li>
                <li>Basic budgeting</li>
              </ul>
            </div>
            <div class="ud-pricing-footer">
              <a href="{% url 'finance_tracker:dashboard' %}" class="ud-main-btn ud-border-btn">
                Activate Free Plan
              </a>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-10">
          <div
            class="ud-single-pricing active wow fadeInUp"
            data-wow-delay=".1s">
            <span class="ud-popular-tag">POPULAR</span>
            <div class="ud-pricing-header">
              <h4>$ 19.99/mo</h4>
            </div>
            <div class="ud-pricing-body">
              <ul class="pricing-list">
                <li>2 Users</li>
                <li>50 File uploads</li>
                <li>Unlimited access</li>
                <li>Comprehensive budgeting</li>
              </ul>
            </div>
            <div class="ud-pricing-footer">
              <a href="{% url 'finance_tracker:dashboard' %}" class="ud-main-btn ud-white-btn">
                Purchase Now
              </a>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-10">
          <div
            class="ud-single-pricing last-item wow fadeInUp"
            data-wow-delay=".15s">
            <div class="ud-pricing-header">
              <h3>FAMILY PLAN</h3>
              <h4>$ 29.99/mo</h4>
            </div>
            <div class="ud-pricing-body">
              <ul class="pricing-list">
                <li>10 Users</li>
                <li>500 File uploads</li>
                <li>Unlimited access</li>
                <li>Comprehensive budgeting</li>
              </ul>
            </div>
            <div class="ud-pricing-footer">
              <a href="{% url 'finance_tracker:dashboard' %}" class="ud-main-btn ud-border-btn">
                Purchase Now
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

finance_tracker/templates/finance_tracker/components/sidebar.html
{% comment %} Has inline style for menu width, wouldn't work when linked with ID {% endcomment %}
<div class="offcanvas offcanvas-start offcanvas-dark bg-dark side-menu-mobile" tabindex="-1" id="offcanvas" data-bs-keyboard="false" data-bs-backdrop="false">
    <div class="offcanvas-header">
        <h6 class="offcanvas-title d-none d-sm-block text-light" id="offcanvas">Menu</h6>
        <button  type="button" class="btn-close text-reset btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div id="side_bar_nav" class="offcanvas-body d-flex flex-column px-0">
        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-start flex-grow-1" id="menu">
            <li class="nav-item">
                <a href="{% url 'finance_tracker:home' %}" class="nav-link text-light">
                    <i class="bi bi-house-door"></i><span class="ms-1 d-none d-sm-inline"> Product Page</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'finance_tracker:dashboard' %}" class="nav-link text-light">
                    <i class="bi bi-piggy-bank"></i><span class="ms-1 d-none d-sm-inline"> Dashboard</span> </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'finance_tracker:transaction-list' %}" class="nav-link text-light">
                    <i class="bi bi-list"></i><span class="ms-1 d-none d-sm-inline"> Transactions</span></a>
            </li>
            <li class="nav-item">
                <a href="{% url 'finance_tracker:categories' %}" class="nav-link text-light">
                    <i class="bi bi-tag"></i><span class="ms-1 d-none d-sm-inline"> Categories</span></a>
            </li>
            <li class="nav-item">
                <a href="{% url 'finance_tracker:category-detail' %}" class="nav-link text-light">
                    <i class="bi bi-tag"></i><span class="ms-1 d-none d-sm-inline"> Category Details</span></a>
            </li>
            <li class="nav-item">
                <a href="{% url 'finance_tracker:file_upload' %}" class="nav-link text-light">
                    <i class="fs-5 bi bi-cloud-arrow-up"></i><span class="ms-1 d-none d-sm-inline"> Upload</span></a>
            </li>

            {% comment %} ------------------- User Account ------------------ {% endcomment %}
            <div id="account_nav" class="dropdown mt-auto">
                <li class="nav-item">
                    <a href="{% url 'portfolio:home' %}" class="nav-link text-light">
                        <i class="fs-5 bi-house"></i><span class="ms-1 d-none d-sm-inline"> Portfolio Home</span>
                    </a>
                </li>
                <hr class="menu-divider border border-1">
                <div>
                    <a href="#" class="nav-link dropdown-toggle text-light" id="dropdown" data-bs-toggle="dropdown" aria-expanded="false">
                        {% if user_profile and user_profile.avatar %}
                        <img src="{{ user_profile.avatar.url }}" alt="Profile Picture" class="rounded-circle" style="width: 40px; height: 40px; margin-right: 5px;"><span class="ms-1 d-none d-sm-inline"> {{ user.username }}</span>
                        {% else %}
                        <i class="fs-5 bi bi-person-circle"></i><span class="ms-1 d-none d-sm-inline"> Account</span>
                        {% endif %}
                    </a>
                    <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdown">
                        {% if user.is_authenticated %}
                        <li><a class="dropdown-item" href="{% url 'users:profile_home' %}">My Profile</a></li>
                        <li><a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a></li>
                        {% else %}
                        <li><a class="dropdown-item" href="{% url 'account_login' %}">Login</a></li>
                        <li><a class="dropdown-item" href="{% url 'account_signup' %}">Register</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div> 
            </ul>
        </div>
    </div>
</div>
    
        

finance_tracker/templates/finance_tracker/components/upload_notify.html
<div id="upload-notify-widget" class="d-flex justify-content-center align-items-center">
  <div class="col-md-4">
    <div class="card shadow p-4">
      <div class="mt-3 text-center">
        <p>
          No data yet,
          <br />
          Please upload your bank statement.
        </p>
        <a href="{% url 'finance_tracker:file_upload' %}" id="btn_1" class="btn btn-success mt-3 me-2">Upload <i class="bi bi-file-arrow-up"></i></a>
      </div>
    </div>
  </div>
</div>